CREATE TABLE `platformAuditLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`auditVersion` varchar(32) NOT NULL,
	`auditDate` timestamp NOT NULL,
	`auditorName` varchar(128) NOT NULL,
	`overallStatus` enum('pass','conditional_pass','fail') NOT NULL,
	`artifactHash` varchar(128) NOT NULL,
	`reportUrl` text,
	`layer2Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer3Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer4Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer5Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer6Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer7Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer8Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer9Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer10Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer11Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer12Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer13Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`layer14Status` enum('pass','warning','fail','na') DEFAULT 'na',
	`publicSummary` text,
	`internalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `platformAuditLogs_id` PRIMARY KEY(`id`)
);
