/**
 * server/payments/types.ts
 *
 * Core payment abstraction types for Living Nexus.
 *
 * Every payment provider implements the PaymentProvider interface.
 * The platform never calls Stripe, Lightning, or any provider directly —
 * it calls through this interface. Providers are interchangeable infrastructure.
 *
 * Philosophy: Payment providers are infrastructure, not identity.
 * A creator should be able to switch from Stripe to Lightning without
 * changing their storefront, profile, or any platform API.
 */

// ─── Provider Identity ────────────────────────────────────────────────────────

export type ProviderId =
  | "stripe"
  | "bitcoin"
  | "lightning"
  | "usdc"
  | "paypal"
  | "square"
  | "ach"
  | "apple_pay"
  | "google_pay"
  | "cashapp"
  | "venmo";

export type PaymentType = "fiat" | "crypto" | "stablecoin" | "hybrid";
export type SettlementSpeed = "instant" | "minutes" | "hours" | "days";
export type CustodyModel = "custodial" | "non_custodial" | "hybrid";

// ─── Checkout / Payment Request ───────────────────────────────────────────────

export interface CheckoutParams {
  /** Internal Living Nexus payment intent type */
  intentType: "tip" | "license" | "slots" | "project_donation" | "platform_gift" | "activation" | "subscription";
  /** Amount in the smallest unit of the currency (cents for USD, sats for BTC) */
  amountSmallestUnit: number;
  /** ISO 4217 currency code or crypto ticker: "USD", "BTC", "ETH", "USDC" */
  currency: string;
  /** Human-readable description shown to the payer */
  description: string;
  /** Metadata passed through to webhook / verification */
  metadata: Record<string, string>;
  /** Creator receiving the payment (for provider routing) */
  creatorUserId?: number;
  /** Payer user ID (may be undefined for anonymous) */
  payerUserId?: number;
  /** URL to redirect to after successful payment (fiat providers) */
  successUrl?: string;
  /** URL to redirect to after cancelled payment (fiat providers) */
  cancelUrl?: string;
  /** For subscriptions: billing interval */
  interval?: "month" | "quarter" | "year";
}

export interface CheckoutResult {
  /** Provider-specific payment/invoice ID */
  providerPaymentId: string;
  /** Provider ID that created this checkout */
  providerId: ProviderId;
  /** For fiat/hosted: redirect URL for the payer */
  checkoutUrl?: string;
  /** For crypto: payment address or invoice */
  paymentAddress?: string;
  /** For Lightning: BOLT11 invoice string */
  lightningInvoice?: string;
  /** For Lightning: LNURL pay string */
  lnurlPay?: string;
  /** QR code data URI (base64 PNG) — generated by provider or abstraction layer */
  qrCodeDataUri?: string;
  /** Expiry timestamp (Unix ms) — especially important for Lightning invoices */
  expiresAt?: number;
  /** Amount in smallest unit (may differ from input if provider normalizes) */
  amountSmallestUnit: number;
  currency: string;
  /** Provider-specific raw response for debugging */
  raw?: unknown;
}

// ─── Payment Verification ─────────────────────────────────────────────────────

export interface VerifyParams {
  providerPaymentId: string;
  providerId: ProviderId;
  /** Raw webhook payload (for signature verification) */
  webhookPayload?: unknown;
  webhookSignature?: string;
  webhookHeaders?: Record<string, string>;
}

export interface PaymentRecord {
  providerPaymentId: string;
  providerId: ProviderId;
  status: "pending" | "confirmed" | "failed" | "expired" | "refunded";
  amountSmallestUnit: number;
  currency: string;
  /** Normalized USD equivalent (for accounting) */
  amountUsdCents?: number;
  intentType: string;
  metadata: Record<string, string>;
  confirmedAt?: Date;
  /** On-chain transaction hash (Bitcoin, USDC) */
  txHash?: string;
  /** Number of confirmations (Bitcoin) */
  confirmations?: number;
  raw?: unknown;
}

// ─── Webhook / Event Framework ────────────────────────────────────────────────

export type WebhookEventType =
  | "payment.confirmed"
  | "payment.failed"
  | "payment.expired"
  | "payment.refunded"
  | "subscription.created"
  | "subscription.renewed"
  | "subscription.cancelled"
  | "subscription.payment_failed"
  | "payout.sent"
  | "payout.failed";

export interface WebhookEvent {
  eventType: WebhookEventType;
  providerId: ProviderId;
  providerEventId: string;
  payment?: PaymentRecord;
  raw: unknown;
}

// ─── Provider Capabilities ────────────────────────────────────────────────────

export interface ProviderCapabilities {
  oneTimePayments: boolean;
  subscriptions: boolean;
  tips: boolean;
  micropayments: boolean;     // sub-$1 payments
  refunds: boolean;
  payouts: boolean;           // platform → creator payouts
  webhooks: boolean;
  qrCode: boolean;
  anonymous: boolean;         // accepts payments without payer account
  custodyModel: CustodyModel;
  settlementSpeed: SettlementSpeed;
  paymentType: PaymentType;
  minAmountUsdCents: number;
  maxAmountUsdCents?: number;
  supportedCurrencies: string[];
}

// ─── Creator Provider Config ──────────────────────────────────────────────────

export interface CreatorProviderConfig {
  enabled: boolean;
  /** Provider-specific config — varies per provider */
  config: Record<string, string | boolean | number>;
  /** When the creator enabled this provider */
  enabledAt?: Date;
  /** Verification status (e.g. Stripe Connect onboarded, BTC address verified) */
  verified: boolean;
  verifiedAt?: Date;
}

export interface CreatorPaymentSettings {
  creatorUserId: number;
  providers: Partial<Record<ProviderId, CreatorProviderConfig>>;
  /** Default provider for new payments (creator's preference) */
  defaultProvider?: ProviderId;
  /** Whether to show all enabled providers to fans or just the default */
  showAllProviders: boolean;
  updatedAt: Date;
}

// ─── Balance / Payout ─────────────────────────────────────────────────────────

export interface BalanceResult {
  providerId: ProviderId;
  available: number;
  pending: number;
  currency: string;
  /** USD equivalent */
  availableUsdCents?: number;
}

// ─── The Core Provider Interface ─────────────────────────────────────────────
//
// Every payment provider implements this interface.
// The platform calls through this interface — never directly.
//
export interface PaymentProvider {
  /** Unique identifier for this provider */
  readonly id: ProviderId;
  /** Human-readable name */
  readonly name: string;
  /** Provider capabilities */
  readonly capabilities: ProviderCapabilities;

  /**
   * Create a payment request / checkout session.
   * Returns a CheckoutResult with everything needed to present payment to the fan.
   */
  createCheckout(params: CheckoutParams): Promise<CheckoutResult>;

  /**
   * Verify a payment — called after webhook or polling.
   * Returns a normalized PaymentRecord regardless of provider.
   */
  verifyPayment(params: VerifyParams): Promise<PaymentRecord>;

  /**
   * Handle an inbound webhook from this provider.
   * Verifies signature, parses event, returns normalized WebhookEvent.
   */
  handleWebhook(payload: unknown, headers: Record<string, string>): Promise<WebhookEvent>;

  /**
   * Get creator's balance with this provider (optional).
   * Not all providers support programmatic balance queries.
   */
  getBalance?(creatorUserId: number, config: CreatorProviderConfig): Promise<BalanceResult>;

  /**
   * Validate a creator's provider config (e.g. verify BTC address format,
   * check Strike API key, verify Stripe Connect status).
   */
  validateCreatorConfig(config: Record<string, string | boolean | number>): Promise<{
    valid: boolean;
    errors: string[];
    warnings: string[];
  }>;

  /**
   * Check if this provider is properly configured at the platform level.
   * (e.g. Stripe secret key present, Strike API key present)
   */
  isConfigured(): boolean;
}

// ─── Transaction Log ──────────────────────────────────────────────────────────
// Unified transaction log across all providers — stored in DB.

export interface TransactionLogEntry {
  id?: number;
  providerId: ProviderId;
  providerPaymentId: string;
  intentType: string;
  status: "pending" | "confirmed" | "failed" | "expired" | "refunded";
  amountSmallestUnit: number;
  currency: string;
  amountUsdCents?: number;
  payerUserId?: number;
  creatorUserId?: number;
  metadata: Record<string, string>;
  txHash?: string;
  confirmations?: number;
  createdAt?: Date;
  confirmedAt?: Date;
  updatedAt?: Date;
  raw?: string; // JSON stringified raw provider response
}
