export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  workerSecret: process.env.LN_WORKER_SECRET ?? "",
  registryApiPepper: process.env.LN_REGISTRY_API_PEPPER ?? "",
  registryApiBaseUrl: process.env.LN_REGISTRY_API_BASE_URL ?? "",
  registryApiKey: process.env.LN_REGISTRY_API_KEY ?? "",
  registryApiTimeoutMs: process.env.LN_REGISTRY_API_TIMEOUT_MS ?? "",
  registryApiKeyVersion: process.env.LN_REGISTRY_API_KEY_VERSION ?? "",
  nexusAssertionPrivateKey: process.env.LN_NEXUS_ASSERTION_PRIVATE_KEY ?? "",
  nexusAssertionIssuer: process.env.LN_NEXUS_ASSERTION_ISSUER ?? "https://www.livingnexus.org",
  nexusAssertionAudience: process.env.LN_NEXUS_ASSERTION_AUDIENCE ?? "nexus-staging",
  cloudWorkerUrl: process.env.CLOUD_WORKER_URL ?? "",
  mcpReadToken: process.env.MCP_READ_TOKEN ?? "",
  manusApiKey: process.env.MANUS_API_KEY ?? "",
};
