/**
 * @service  GcodeParser
 * @domain   3D Print Provenance — G-code file analysis
 *
 * Parses G-code files to extract:
 *  1. Embedded slicer thumbnail (Base64 PNG in comment block)
 *     Supported slicers: PrusaSlicer, Bambu Studio, Cura, SuperSlicer, OrcaSlicer
 *  2. Print statistics: layer count, estimated time, filament usage, slicer name/version, bed size
 *
 * The thumbnail is returned as a Buffer (PNG) ready for storagePut().
 * Print stats are returned as a typed object for storage in printStatsJson.
 */

export interface PrintStats {
  layerCount?: number;
  estimatedPrintTime?: string;      // Human-readable, e.g. "2h 34m"
  filamentUsedMm?: number;
  filamentUsedG?: number;
  slicer?: string;                  // e.g. "PrusaSlicer", "Bambu Studio", "Cura"
  slicerVersion?: string;
  bedSizeX?: number;
  bedSizeY?: number;
  bedSizeZ?: number;
  nozzleDiameter?: number;
  layerHeight?: number;
  infillPercent?: number;
  printTemperature?: number;
  bedTemperature?: number;
}

export interface GcodeParseResult {
  thumbnailBuffer: Buffer | null;   // PNG image bytes, or null if no thumbnail found
  printStats: PrintStats;
}

/**
 * Parse a G-code file buffer and extract thumbnail + print statistics.
 * Designed to be fast and fail-open: any parsing error returns partial results.
 */
export function parseGcode(buffer: Buffer): GcodeParseResult {
  const stats: PrintStats = {};
  let thumbnailBuffer: Buffer | null = null;

  // Only scan the first 512KB for headers (thumbnails and metadata are always at the top)
  const headerBytes = buffer.slice(0, Math.min(buffer.length, 512 * 1024));
  const text = headerBytes.toString("utf-8");
  const lines = text.split("\n");

  // ── Thumbnail extraction ──────────────────────────────────────────────────
  // PrusaSlicer / SuperSlicer / OrcaSlicer format:
  //   ; thumbnail begin <W>x<H> <size>
  //   ; <base64 data>
  //   ; thumbnail end
  //
  // Bambu Studio format:
  //   ; THUMBNAIL_BEGIN W=<W> H=<H>
  //   ; <base64 data>
  //   ; THUMBNAIL_END
  //
  // Cura format:
  //   ;THUMBNAIL_BEGIN:<W>x<H>:<size>
  //   ;<base64 data>
  //   ;THUMBNAIL_END

  let inThumbnail = false;
  let thumbnailChunks: string[] = [];
  let bestThumbnailSize = 0; // prefer larger thumbnails

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // PrusaSlicer / SuperSlicer / OrcaSlicer begin
    const prusaBegin = line.match(/^;\s*thumbnail begin\s+(\d+)x(\d+)\s+(\d+)/i);
    if (prusaBegin) {
      const w = parseInt(prusaBegin[1]);
      const h = parseInt(prusaBegin[2]);
      const size = parseInt(prusaBegin[3]);
      if (size > bestThumbnailSize) {
        bestThumbnailSize = size;
        inThumbnail = true;
        thumbnailChunks = [];
      }
      continue;
    }

    // Bambu Studio begin
    const bambuBegin = line.match(/^;\s*THUMBNAIL_BEGIN\s+W=(\d+)\s+H=(\d+)/i);
    if (bambuBegin) {
      inThumbnail = true;
      thumbnailChunks = [];
      continue;
    }

    // Cura begin
    const curaBegin = line.match(/^;THUMBNAIL_BEGIN:(\d+)x(\d+):(\d+)/i);
    if (curaBegin) {
      const size = parseInt(curaBegin[3]);
      if (size > bestThumbnailSize) {
        bestThumbnailSize = size;
        inThumbnail = true;
        thumbnailChunks = [];
      }
      continue;
    }

    // End markers
    if (line.match(/^;\s*(thumbnail end|THUMBNAIL_END)/i)) {
      if (inThumbnail && thumbnailChunks.length > 0) {
        try {
          const b64 = thumbnailChunks.join("").replace(/\s/g, "");
          thumbnailBuffer = Buffer.from(b64, "base64");
        } catch {
          // ignore decode errors
        }
      }
      inThumbnail = false;
      thumbnailChunks = [];
      continue;
    }

    // Collect base64 lines inside thumbnail block
    if (inThumbnail) {
      // Strip leading semicolon and whitespace
      const data = line.replace(/^;\s*/, "");
      if (data.length > 0) {
        thumbnailChunks.push(data);
      }
      continue;
    }
  }

  // ── Print statistics extraction ───────────────────────────────────────────
  // We scan all comment lines for known slicer metadata patterns.

  for (const line of lines) {
    const l = line.trim();
    if (!l.startsWith(";")) continue;
    const comment = l.slice(1).trim();

    // Slicer identification
    // PrusaSlicer: ; generated by PrusaSlicer 2.7.4
    const prusaSlicer = comment.match(/generated by (PrusaSlicer|SuperSlicer|OrcaSlicer)\s+([\d.]+)/i);
    if (prusaSlicer) {
      stats.slicer = prusaSlicer[1];
      stats.slicerVersion = prusaSlicer[2];
    }

    // Bambu Studio: ; BAMBU_STUDIO_VERSION = 1.9.4
    const bambuVersion = comment.match(/BAMBU_STUDIO_VERSION\s*=\s*([\d.]+)/i);
    if (bambuVersion) {
      stats.slicer = "Bambu Studio";
      stats.slicerVersion = bambuVersion[1];
    }

    // Cura: ;Generated with Cura_SteamEngine 5.7.2
    const curaVersion = comment.match(/Generated with Cura_SteamEngine\s+([\d.]+)/i);
    if (curaVersion) {
      stats.slicer = "Cura";
      stats.slicerVersion = curaVersion[1];
    }

    // Layer count
    // PrusaSlicer: ; total layers count = 234
    // Bambu: ; LAYER_COUNT = 234
    const layerCount = comment.match(/(?:total layers count|LAYER_COUNT)\s*[=:]\s*(\d+)/i);
    if (layerCount) stats.layerCount = parseInt(layerCount[1]);

    // Estimated print time
    // PrusaSlicer: ; estimated printing time (normal mode) = 2h 34m 12s
    // Bambu: ; TIME_COST = 9252
    const prusaTime = comment.match(/estimated printing time.*?=\s*(.+)/i);
    if (prusaTime) stats.estimatedPrintTime = prusaTime[1].trim();

    const bambuTimeSec = comment.match(/TIME_COST\s*=\s*(\d+)/i);
    if (bambuTimeSec && !stats.estimatedPrintTime) {
      const secs = parseInt(bambuTimeSec[1]);
      const h = Math.floor(secs / 3600);
      const m = Math.floor((secs % 3600) / 60);
      stats.estimatedPrintTime = h > 0 ? `${h}h ${m}m` : `${m}m`;
    }

    // Filament used
    // PrusaSlicer: ; filament used [mm] = 2345.67
    // PrusaSlicer: ; filament used [g] = 7.01
    // Bambu: ; FILAMENT_USED = 2345.67
    const filamentMm = comment.match(/filament used \[mm\]\s*=\s*([\d.]+)/i);
    if (filamentMm) stats.filamentUsedMm = parseFloat(filamentMm[1]);

    const filamentG = comment.match(/filament used \[g\]\s*=\s*([\d.]+)/i);
    if (filamentG) stats.filamentUsedG = parseFloat(filamentG[1]);

    const bambuFilament = comment.match(/FILAMENT_USED\s*=\s*([\d.]+)/i);
    if (bambuFilament && !stats.filamentUsedMm) stats.filamentUsedMm = parseFloat(bambuFilament[1]);

    // Bed size / print volume
    // PrusaSlicer: ; bed_shape = 0x0,250x0,250x210,0x210
    const bedShape = comment.match(/bed_shape\s*=\s*0x0,(\d+)x0,\1x(\d+)/i);
    if (bedShape) {
      stats.bedSizeX = parseInt(bedShape[1]);
      stats.bedSizeY = parseInt(bedShape[2]);
    }

    // Max Z
    // PrusaSlicer: ; max_print_height = 200
    const maxZ = comment.match(/max_print_height\s*=\s*([\d.]+)/i);
    if (maxZ) stats.bedSizeZ = parseFloat(maxZ[1]);

    // Nozzle diameter
    // PrusaSlicer: ; nozzle_diameter = 0.4
    const nozzle = comment.match(/nozzle_diameter\s*=\s*([\d.]+)/i);
    if (nozzle) stats.nozzleDiameter = parseFloat(nozzle[1]);

    // Layer height
    // PrusaSlicer: ; layer_height = 0.2
    const layerHeight = comment.match(/layer_height\s*=\s*([\d.]+)/i);
    if (layerHeight) stats.layerHeight = parseFloat(layerHeight[1]);

    // Infill percent
    // PrusaSlicer: ; fill_density = 15%
    const infill = comment.match(/fill_density\s*=\s*(\d+)/i);
    if (infill) stats.infillPercent = parseInt(infill[1]);

    // Print temperature
    // PrusaSlicer: ; temperature = 215
    const printTemp = comment.match(/^temperature\s*=\s*(\d+)/i);
    if (printTemp) stats.printTemperature = parseInt(printTemp[1]);

    // Bed temperature
    // PrusaSlicer: ; bed_temperature = 60
    const bedTemp = comment.match(/bed_temperature\s*=\s*(\d+)/i);
    if (bedTemp) stats.bedTemperature = parseInt(bedTemp[1]);
  }

  return { thumbnailBuffer, printStats: stats };
}
