/**
 * AiDisclosurePill — shared component for AI disclosure badges.
 *
 * Replaces all inline badge implementations across TrackCard, ExplorePage,
 * MobilePlayerPanel, DiscoverPage, and SongDetailPage.
 *
 * Label taxonomy (aligned with Living Nexus Covenant):
 *   original            → Human-Made
 *   ai_assisted         → AI-Assisted
 *   ai_generated        → AI-Generated
 *
 * aiConsent taxonomy (training permission):
 *   prohibited          → No AI Training
 *   permitted_attribution → Attribution Required
 *   permitted           → Open Training
 */

import React from "react";
import { Cpu, Sparkles, Music, ShieldOff, Info, CheckCircle, PenLine } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

// ─── AI Disclosure (how much AI was used in creation) ─────────────────────────

export type AiDisclosureValue = "original" | "ai_assisted" | "ai_generated" | "human_authored_ai_instrument" | null | undefined;

interface DisclosureConfig {
  label: string;
  shortLabel: string;
  icon: React.ReactNode;
  color: string;
  bg: string;
  border: string;
  tooltip: string;
}

function getDisclosureConfig(value: AiDisclosureValue): DisclosureConfig {
  switch (value) {
    case "human_authored_ai_instrument":
      return {
        label: "Human-Authored via AI Instrument",
        shortLabel: "HAAI",
        icon: <PenLine className="w-3 h-3" />,
        color: "var(--ln-gold)",
        bg: "rgba(196,154,40,0.08)",
        border: "rgba(196,154,40,0.2)",
        tooltip: "The creator authored the intent, vision, and direction. AI was the instrument — not the author. Directorial declaration is on record.",
      };
    case "ai_generated":
      return {
        label: "AI-Generated",
        shortLabel: "AI",
        icon: <Cpu className="w-3 h-3" />,
        color: "var(--ln-gold)",
        bg: "rgba(196,154,40,0.09)",
        border: "rgba(196,154,40,0.26)",
        tooltip: "This work was fully generated by AI. The creator directed the process but the audio/content was produced by an AI system.",
      };
    case "ai_assisted":
      return {
        label: "AI-Assisted",
        shortLabel: "AI+",
        icon: <Sparkles className="w-3 h-3" />,
        color: "var(--ln-gold)",
        bg: "rgba(196,154,40,0.09)",
        border: "rgba(196,154,40,0.26)",
        tooltip: "This work was created by a human with AI assistance — tools like stem separation, mastering, or arrangement suggestions were used.",
      };
    case "original":
    default:
      return {
        label: "Human-Made",
        shortLabel: "HM",
        icon: <Music className="w-3 h-3" />,
        color: "var(--ln-seal-bright)",
        bg: "rgba(74,222,128,0.1)",
        border: "rgba(58,138,86,0.3)",
        tooltip: "This work was created entirely by a human. No AI was used in the creative process.",
      };
  }
}

// ─── AI Consent (training permission) ────────────────────────────────────────

export type AiConsentValue = "prohibited" | "permitted_attribution" | "permitted" | null | undefined;

interface ConsentConfig {
  label: string;
  icon: React.ReactNode;
  color: string;
  bg: string;
  border: string;
  tooltip: string;
}

function getConsentConfig(value: AiConsentValue): ConsentConfig {
  switch (value) {
    case "permitted":
      return {
        label: "Open Training",
        icon: <CheckCircle className="w-3 h-3" />,
        color: "var(--ln-seal-bright)",
        bg: "rgba(74,222,128,0.1)",
        border: "rgba(58,138,86,0.3)",
        tooltip: "The creator permits AI systems to train on this work without attribution requirements.",
      };
    case "permitted_attribution":
      return {
        label: "Attribution Required",
        icon: <Info className="w-3 h-3" />,
        color: "var(--ln-gold)",
        bg: "rgba(196,154,40,0.09)",
        border: "rgba(196,154,40,0.26)",
        tooltip: "AI training is permitted only with proper attribution to the original creator.",
      };
    case "prohibited":
    default:
      return {
        label: "No AI Training",
        icon: <ShieldOff className="w-3 h-3" />,
        color: "var(--ln-ember)",
        bg: "rgba(239,68,68,0.1)",
        border: "rgba(196,68,10,0.3)",
        tooltip: "The creator has explicitly prohibited AI systems from training on this work. This is protected under the Living Nexus Covenant.",
      };
  }
}

// ─── Components ──────────────────────────────────────────────────────────────

interface AiDisclosurePillProps {
  value: AiDisclosureValue;
  /** "full" shows icon + full label, "compact" shows icon + short label, "icon" shows icon only */
  size?: "full" | "compact" | "icon";
  showTooltip?: boolean;
  className?: string;
}

export function AiDisclosurePill({
  value,
  size = "compact",
  showTooltip = true,
  className = "",
}: AiDisclosurePillProps) {
  const cfg = getDisclosureConfig(value);

  const pill = (
    <span
      className={`inline-flex items-center gap-1 rounded-full font-medium select-none ${className}`}
      style={{
        color: cfg.color,
        background: cfg.bg,
        border: `1px solid ${cfg.border}`,
        padding: size === "icon" ? "2px 6px" : "2px 8px",
        fontSize: "10px",
        lineHeight: "16px",
        letterSpacing: "0.04em",
      }}
    >
      {cfg.icon}
      {size === "full" && <span>{cfg.label}</span>}
      {size === "compact" && <span>{cfg.shortLabel}</span>}
    </span>
  );

  if (!showTooltip) return pill;

  return (
    <TooltipProvider delayDuration={300}>
      <Tooltip>
        <TooltipTrigger asChild>{pill}</TooltipTrigger>
        <TooltipContent
          side="top"
          className="max-w-[240px] text-xs"
          style={{
            background: "var(--ln-coal)",
            border: "1px solid #C3AB7D",
            color: "var(--ln-parchment)",
          }}
        >
          <p className="font-semibold mb-0.5">{cfg.label}</p>
          <p className="opacity-80">{cfg.tooltip}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

interface AiConsentPillProps {
  value: AiConsentValue;
  size?: "full" | "compact" | "icon";
  showTooltip?: boolean;
  className?: string;
}

export function AiConsentPill({
  value,
  size = "compact",
  showTooltip = true,
  className = "",
}: AiConsentPillProps) {
  const cfg = getConsentConfig(value);

  const pill = (
    <span
      className={`inline-flex items-center gap-1 rounded-full font-medium select-none ${className}`}
      style={{
        color: cfg.color,
        background: cfg.bg,
        border: `1px solid ${cfg.border}`,
        padding: size === "icon" ? "2px 6px" : "2px 8px",
        fontSize: "10px",
        lineHeight: "16px",
        letterSpacing: "0.04em",
      }}
    >
      {cfg.icon}
      {size !== "icon" && (
        <span>{size === "full" ? cfg.label : cfg.label.split(" ")[0]}</span>
      )}
    </span>
  );

  if (!showTooltip) return pill;

  return (
    <TooltipProvider delayDuration={300}>
      <Tooltip>
        <TooltipTrigger asChild>{pill}</TooltipTrigger>
        <TooltipContent
          side="top"
          className="max-w-[240px] text-xs"
          style={{
            background: "var(--ln-coal)",
            border: "1px solid #C3AB7D",
            color: "var(--ln-parchment)",
          }}
        >
          <p className="font-semibold mb-0.5">{cfg.label}</p>
          <p className="opacity-80">{cfg.tooltip}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

/**
 * Combined pill row — shows both disclosure and consent side by side.
 * Use this in detail views (SongDetailPage) where both values are shown.
 */
export function AiDisclosureRow({
  disclosure,
  consent,
  size = "full",
}: {
  disclosure: AiDisclosureValue;
  consent: AiConsentValue;
  size?: "full" | "compact";
}) {
  return (
    <div className="flex items-center gap-2 flex-wrap">
      <AiDisclosurePill value={disclosure} size={size} />
      <AiConsentPill value={consent} size={size} />
    </div>
  );
}
